✨ add feature to add branding image for the Android 12+
SimformSolutionsPvtLtd/splash_master pull request #48
Opened 2024-12-23 13:24 UTC by apurva010

# Description
- Added support to add branding image for Android 12+.

## Checklist

- [ ] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [X] I have followed the [Contributor Guide] when preparing my PR.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [X] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [X] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [X] No, this PR is not a breaking change.

## Related Issues

[Contributor Guide]: https://github.com/SimformSolutionsPvtLtd/splash_master/blob/main/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org

2024-12-24 09:48 UTC, ujas-m-simformsolutions commented on lib/cmd/android_splash.dart
> +  sourceImage.copySync(imagePath);
As discussed use copy

2024-12-24 09:48 UTC, ujas-m-simformsolutions commented on lib/cmd/android_splash.dart
> +    sourceImage.copySync(imagePath);
^^

2024-12-24 09:49 UTC, ujas-m-simformsolutions requested changes

2024-12-24 09:49 UTC, ujas-m-simformsolutions commented on lib/cmd/android_splash.dart
> +  brandingImageSource.copySync(imagePath);
^^

2024-12-24 10:01 UTC, ujas-m-simformsolutions approved these changes

2024-12-30 09:03 UTC, dhaval-k-simformsolutions approved these changes

2024-12-30 09:03 UTC, merged